---
# handlers file for webserver
- name: restart_httpd
  systemd:
    name: httpd
    state: started
    enabled: true         
    
- name:  check the status of services 
  shell:
    systemctl status httpd      
    systemctl status mariadb  
