---
# tasks file for datadisk

    - name: Install parted
      package:
        name: parted
        state: present 

    - name: Add a new partition with a size of 4 GB initialized with XFS
      parted:
        device: /dev/sdc
        number: 2
        flags: [ lvm ]
        state: present
        part_end: 4GB

    - name: Mount the file system as xfs
      filesystem:
        fstype: xfs
        dev: /dev/sdc1

    - name: Create directory /part1
      file:
        path: /part1
        state: directory
        mode: '0755'

    - name: Mount 4GB partition to /part1
      mount:
        fstype: xfs
        src: /dev/sdc1
        path: /part1
        state: mounted

    - name: Add a new partition with a size of 5 GB initialized with ext4
      parted:
        device: /dev/sdc
        number: 2
        flags: [ lvm ]
        state: present
        part_start: 4.5GB
        part_end: 9.5GB

    - name: Mount the file system as ext4
      filesystem:
        fstype: ext4
        dev: /dev/sdc2

    - name: Create directory /part2
      file:
        path: /part2
        state: directory
        mode: '0755'   

    - name: Mount 5GB partition to /part2
      mount:
        fstype: ext4
        src: /dev/sdc2
        path: /part2
        state: mounted